<a href="https://colab.research.google.com/github/Larychev93/tensorflow-learning/blob/main/Tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Import tensor
import tensorflow as tf
import numpy as np

print(tf.__version__)


2.15.0


In [3]:
# Create scalar

scalar = tf.constant(7)
print(scalar)

tf.Tensor(7, shape=(), dtype=int32)


In [4]:
# Check the number of dimensions
scalar.ndim

0

In [5]:
# Create vector

vector = tf.constant([7, 10])
vector.ndim

1

In [6]:
# Create matrix
matrix = tf.constant([
    [7, 10],
    [10, 7]
])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [10,  7]], dtype=int32)>

In [7]:
# Create another matrix
anotherMatrix = tf.constant([
    [10., 7.],
    [3., 2.],
    [8., 9.]
], dtype=tf.float16)

anotherMatrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [8]:
# Create tensor
tensor = tf.constant([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]],
    [[13, 14, 15], [16, 17, 18]]
])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

All of the above variables we've created are actually tensors. But you may also hear them referred to as their different names (the ones we gave them):

*   scalar: a single number.
*   vector: a number with direction (e.g. wind speed with direction).
*   matrix: a 2-dimensional array of numbers.
*   tensor: an n-dimensional array of numbers (where n can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector).

![difference between scalar, vector, matrix, tensor](https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/images/00-scalar-vector-matrix-tensor.png)



# Creating tennsor with tf.Variable

In [9]:
# Create the same tensor with tf.Variable() and tf.constant()
changeableTensor = tf.Variable([10, 7])
unchangeableTensor = tf.constant([10, 7])
changeableTensor, unchangeableTensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

To change an element of a tf.Variable() tensor requires the assign() method.

In [10]:
changeableTensor[0].assign(7)
changeableTensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

# Creating random tensors

Random tensors are tensors of some arbitrary size which contain random numbers.

Why would you want to create random tensors?

This is what neural networks use to intialize their weights (patterns) that they're trying to learn in the data.

For example, the process of a neural network learning often involves taking a random n-dimensional array of numbers and refining them until they represent some kind of pattern (a compressed way to represent the original data).

In [11]:
# Create two random (but the same) tensors
randomTensor1 = tf.random.Generator.from_seed(42)
randomTensor1 = randomTensor1.normal(shape=(3,2))

randomTensor2 = tf.random.Generator.from_seed(42)
randomTensor2 = randomTensor2.normal(shape=(3,2))

randomTensor1, randomTensor2, randomTensor1 == randomTensor2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [12]:
# Shuffle a tensor (valuable for when you want to shuffle your data)
notShuffled = tf.constant([
    [10, 7],
    [3, 4],
    [2, 5]
])

tf.random.shuffle(notShuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [13]:
# Set the global random seed
tf.random.set_seed(42) # if you comment this out you'll get different results

# Set the operation random seed
tf.random.shuffle(notShuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

# Other ways to make tensors
Though you might rarely use these (remember, many tensor operations are done behind the scenes for you), you can use tf.ones() to create a tensor of all ones and tf.zeros() to create a tensor of all zeros.

# Getting information from tensors (shape, rank, size)

* Shape: The length (number of elements) of each of the dimensions of a tensor.
* Rank: The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n.
* Axis or Dimension: A particular dimension of a tensor.
* Size: The total number of items in the tensor.

In [14]:
rank4Tensor = tf.zeros(shape=[2, 3, 4, 5])

rank4Tensor.shape, rank4Tensor.ndim, tf.size(rank4Tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [15]:
# Get various attributes of tensor
print("Datatype of every element:", rank4Tensor.dtype)
print("Number of dimensions (rank):", rank4Tensor.ndim)
print("Shape of tensor:", rank4Tensor.shape)
print("Elements along axis 0 of tensor:", rank4Tensor.shape[0])
print("Elements along last axis of tensor:", rank4Tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank4Tensor).numpy()) # .numpy() converts to NumPy array

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


## Indexing *tensors*

You can also index tensors just like Python lists.

In [16]:
someList = [2, 3, 10, 12]
someList[:2]

rank4Tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [17]:
# create 2 rank tensor
rank2Tensor = tf.constant([
    [10, 7],
    [3, 4]
])
rank2Tensor[:2]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [18]:
# Get the last item of each row
rank2Tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [19]:
# add an extra dimension to our rank 2 tensor
rank3Tensor = rank2Tensor[..., tf.newaxis]
rank3Tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [20]:
# alternative way
tf.expand_dims(rank2Tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [21]:
# alternative 0 axes
tf.expand_dims(rank2Tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

## Manipulating tensors (tensor operations)

Finding patterns in tensors (numerical representation of data) requires manipulating them.

Again, when building models in TensorFlow, much of this pattern discovery is done for you.

### Basic operations

You can perform many of the basic mathematical operations directly on tensors using Python operators such as, `+`, `-`, `*`.

In [22]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([
    [10, 7],
    [3, 4]
])

tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

Since we used `tf.constant()`, the original tensor is unchanged (the addition gets done on a copy).

In [23]:
# Multiplication also works
tensor * 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 14],
       [ 6,  8]], dtype=int32)>

In [24]:
# Subtraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

### Matrix mutliplication

One of the most common operations in machine learning algorithms is [matrix multiplication](https://www.mathsisfun.com/algebra/matrix-multiplying.html).

[visualize](http://matrixmultiplication.xyz/)


Under the hood, we SHOULD MULTIPLY ROW * COLUMN

[10 7] [10 7]
[3 4] [3 4]

10*10 + 7 *3= 121
10* 7 + 7*4 = 98

3* 10 + 4* 3 = 42

3*7 + 4*4 = 37

In [25]:
# Matrix multiplication in TensorFlow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [26]:
# Matrix multiplication with Python operator '@'
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

Both of these examples work because our `tensor` variable is of shape (2, 2).

What if we created some tensors which had mismatched shapes?

In [27]:
# Create (3, 2) tensor
x = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])

x @ y

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

Trying to matrix multiply two tensors with the shape `(3, 2)` errors because the inner dimensions don't match.

We need to either:
* Reshape X to `(2, 3)` so it's `(2, 3) @ (3, 2)`.
* Reshape Y to `(3, 2)` so it's `(3, 2) @ (2, 3)`.

We can do this with either:
* [`tf.reshape()`](https://www.tensorflow.org/api_docs/python/tf/reshape) - allows us to reshape a tensor into a defined shape.
* [`tf.transpose()`](https://www.tensorflow.org/api_docs/python/tf/transpose) - switches the dimensions of a given tensor.

![lining up dimensions for dot products](https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/images/00-lining-up-dot-products.png)

Let's try `tf.reshape()` first.

In [ ]:
x @ tf.reshape(y, shape=(2, 3))

In [ ]:
# Example of transpose (3, 2) -> (2, 3)
tf.transpose(x)

In [ ]:
# Try matrix multiplication
tf.matmul(tf.transpose(x), y)

Notice the difference in the resulting shapes when tranposing `X` or reshaping `Y`.

This is because of the 2nd rule mentioned above:
 * `(3, 2) @ (2, 3)` -> `(3, 3)` done with `X @ tf.reshape(Y, shape=(2, 3))`
 * `(2, 3) @ (3, 2)` -> `(2, 2)` done with `tf.matmul(tf.transpose(X), Y)`

This kind of data manipulation is a reminder: you'll spend a lot of your time in machine learning and working with neural networks reshaping data (in the form of tensors) to prepare it to be used with various operations (such as feeding it to a model).



### The dot product

Multiplying matrices by each other is also referred to as the dot product.

You can perform the `tf.matmul()` operation using [`tf.tensordot()`](https://www.tensorflow.org/api_docs/python/tf/tensordot).

In [ ]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(x, tf.transpose(y))

In [ ]:
# Perform matrix multiplicaion between X and Y (reshaped)
tf.matmul(x, tf.reshape(y, shape=(2, 3)))

In [ ]:
# Check the values of Y, reshape Y and transpored Y
print("Normal Y:")
print(y, "\n")

print("Y reshaped to (2,3):")
print(tf.reshape(y, shape=(2,3)), "\n")

print("Y transposed:")
print(tf.transpose(y), "\n")

In [ ]:
tf.matmul(x, tf.transpose(y))

## Changing the data type of tensor


In [ ]:
# Create a new tensor with default data type
b = tf.constant([1.7, 2.7])
b.dtype

c = tf.constant([2, 7, 8])
c.dtype

In [ ]:
# Change from float32 to float16
d = tf.cast(b, dtype=tf.float16)
d.dtype

In [ ]:
# Change from int32 to int16
e = tf.cast(c, dtype=tf.int16)
e.dtype

## Aggregatting tensors

Meaning - unify single units to a group


In [ ]:
# get absolute values
d = tf.constant([-7, - 10])
tf.abs(d)

In [ ]:
# Get the minimum
# Get the maximum
# Get the mean of a tensor
# Get the sum of a tensor

In [ ]:
# Create random tensor with values between 0 and 100 and size of 50
e = tf.constant(np.random.randint(0, 100, 50))
e

In [ ]:
# find minimum
tf.reduce_min(e)

In [ ]:
# find maximum
tf.reduce_max(e)

In [ ]:
# find mean (middle, average)
tf.reduce_mean(e)

In [ ]:
# find the sum
tf.reduce_sum(e)

In [ ]:
# find the variance
import tensorflow_probability as tfp

variance = tfp.stats.variance(e)
variance

## Find the positional minimum and maximum of the tensor

In [ ]:
# Create a new tensor for finding positional minimum and maximum
f = tf.random.uniform(shape=[50])
f

In [ ]:
# find the postopnal max index
tf.argmax(f)

In [ ]:
# find the postopnal max value
f[tf.argmax(f)]

In [ ]:
# find the postopnal min index
tf.argmin(f)

## Squezzing a tensor (removing all single dimensions)


In [ ]:
# Create a tensor to get started
g = tf.constant(tf.random.uniform(shape=[50]), shape=[1, 1, 1, 1, 50])
gSquezzed = tf.squeeze(g)
gSquezzed

## One hot encoding tensors


In [ ]:
# create list of indices
someList = [0, 1, 2, 3] # could be red, green, blue, purple

# one hot encode list of indices
tf.one_hot(someList, depth=4)

# Tensors and NumPy

By default tensors have dtype=float32, where as NumPy arrays have dtype=float64.

This is because neural networks (which are usually built with TensorFlow) can generally work very well with less precision (32-bit rather than 64-bit).

In [29]:
# create a tensor directly from NumPy array
J = tf.constant(np.array([3., 7., 10. ]))

# Convert out tensor back to NumPy array
np.array(J),  type(np.array(J))

#Other way
J.numpy(),  type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

# Finding access to GPUs

In [28]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]